// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kube} from '../models';
import {context} from '../models';
import {app} from '../models';

export function CancelPodStream(arg1:string):Promise<void>;

export function GetContexts():Promise<Array<string>>;

export function GetDeployments():Promise<Array<string>>;

export function GetNamespaces():Promise<Array<string>>;

export function LoadCluster(arg1:string,arg2:string):Promise<void>;

export function Save():Promise<void>;

export function Search(arg1:string,arg2:number):Promise<Array<kube.SearchResult>>;

export function SetDeployment(arg1:string):Promise<Array<string>>;

export function SetNamespace(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Stream():Promise<void>;

export function Test():Promise<app.PodLogMessage>;
