// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContexts() {
  return window['go']['app']['App']['GetContexts']();
}

export function GetDeployments() {
  return window['go']['app']['App']['GetDeployments']();
}

export function GetNamespaces() {
  return window['go']['app']['App']['GetNamespaces']();
}

export function LoadCluster(arg1, arg2) {
  return window['go']['app']['App']['LoadCluster'](arg1, arg2);
}

export function SetDeployment(arg1) {
  return window['go']['app']['App']['SetDeployment'](arg1);
}

export function SetNamespace(arg1) {
  return window['go']['app']['App']['SetNamespace'](arg1);
}

export function Stream() {
  return window['go']['app']['App']['Stream']();
}

export function Test() {
  return window['go']['app']['App']['Test']();
}
