// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDir(arg1) {
  return window['go']['ui']['UI']['ChooseDir'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['ui']['UI']['OpenFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['ui']['UI']['Startup'](arg1);
}
